### PR TITLE
Add integration for Awesome Support

### PR DESCRIPTION
**Pull request by julien731**
Following a user feature request, I have added support for [Awesome Support](https://wordpress.org/plugins/awesome-support/) to your plugin. This is related to issue https://github.com/ThemeAvenue/Awesome-Support/issues/154

### CODE REVIEW

**Comment by mcguffin** [comment]
Wow, thanks! I really appreciate your efforts! 
Just one question before merging: does AwesomeSupport create regular WordPress user accounts for its clients? If yes, I would prefer to rely on the existing options `recaptcha_enable_signup` and `recaptcha_enable_login` instead of introducing new options. I cannot imagine a use case where one would desire different levels of security for user registration – would be like locking the front door while leaving the back door open. What do you think?

**Comment by julien731** [comment]
I was expecting you to bring this up!

For the login part, it would work to use `recaptcha_enable_login`. However, the registration is a bit more specific.

As you know, WordPress allows you to enable / disable registration. Awesome Support also has its own allow / disallow option for registration. This means that, for instance, you can disallow standard registrations through the WordPress form, but still allow it through the Awesome Support form. A user who registered through AS form will be give the *Support User* role.

Because we have kind of 2 points of entry for registration, I added a specific option in your plugin. I also added the option for the Awesome Support login for consistency more that anything else. I think that people could be lost if they saw the option for registration and not for login.

Also, the problem with using `recaptcha_enable_signup` is that the `registration_errors` filter is used in the function `register_new_user`, but Awesome Support uses `wp_insert_user` for adding the new users.

**Comment by julien731** [comment]
Any feedback on this @mcguffin ?

**Comment by mcguffin** [comment]
> Because we have kind of 2 points of entry for registration, I added a specific option in your plugin.

Okay, I agree with this. Different registration forms may require different levels of protection.

> I also added the option for the Awesome Support login for consistency more that anything else. I think that people could be lost if they saw the option for registration and not for login.

Sorry, I don't agree with that one. The AS plugin just utilizes the internal WP login process, just using a different form. The idea behind the recaptcha plugin is to protect processes (like login, password reset, registration, user feedback, ...) not just forms. If you protect only one out of two login forms, your login process is still vulnerable.

**Pull request merged**
